version: 2
jobs:
  build:
    docker:
      - image: newsuk/ecs-agent:latest
    steps:
      - checkout
      - run: printenv
      - run:
          name: Running Pipeline
          command: python ./pipeline.py
