version: 2
jobs:
  build:
    docker:
      - image: newsuk/ecs-agent:latest
    branches:
      only:
        - master
        - staging
        - uat
        - dev
        - /rc-.*/
    steps:
      - checkout
      - run: printenv
      - run:
          name: Running Pipeline
          command: python ./pipeline.py
